---

- name: Converge
  hosts: zookeeper
  pre_tasks:
    - name: installing required libs
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - net-tools
        - netcat
  roles:
    - zookeeper_role
